# ===== Welcome to the Monday Motivation Email generator project ===== #
# This program Emails you motivational quotes on monday from the quotes list we have in quotes.txt file.
# Only one quote will be randomly picked to send.
# This is just a code, if you want it to actually send you email on every monday you have to set event on cloud platform such that it will run this code every monday.
# For now you need to run it to send the email it is not automatic.
# You can try a free cloud platform like pythonanywhere and set event to try this code.

import datetime as dt
import smtplib
import random

MY_EMAIL = "xxxxxxx@gmail.com"  # Dummy email
# The password below is called application password.
# It is generated by going in setting of the above gmail account and turning on 2-step verification
PASSWORD = "tkuzsqldoiluyfzb"  # This is not a dummy password, It is actually generated by google, I put it as it is so you get an idea.

now = dt.datetime.now()
day_of_week = now.weekday()  # Integers returned by weekday() function is listed below.
# If it's Monday today then weekday() function will return 0
# Similarly for Tuesday it will return 1, Wednesday = 2, Thursday = 3, Friday = 4, Saturday = 5 and finally Sunday = 6

if day_of_week == 0:  # we are sending mail on monday that is why we have used 0
    with open("quotes.txt") as quote_file:
        # How to access a entire single line of txt file?
        all_quotes = quote_file.readlines()  # return type is list
        quote = random.choice(all_quotes)

    with smtplib.SMTP("smtp.gmail.com", 587) as connection:
        connection.starttls()
        connection.login(user=MY_EMAIL, password=PASSWORD)
        connection.sendmail(from_addr=MY_EMAIL,
                            to_addrs=MY_EMAIL,
                            msg=f"Subject:Monday Motivation\n\n{quote.strip()}")
